# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# sudo
[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» " 
disabled = false

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red) "

[rlang]
format = "with [ğŸ“ $version](blue bold) "
detect_files = ['']
